name: Sync Folder
on:
  push:
    paths:
      - 'Algorithm/_____保研岛____Python蓝桥杯/**' # 监听文件夹的变化
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if new repository exists
        id: check_repo
        run: |
          NEW_REPO="Lesson_Python_TsingPig"
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.NEW_REPO_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository_owner }}/$NEW_REPO)
          if [ "$RESPONSE" -eq 200 ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create new repository if not exists
        if: steps.check_repo.outputs.exists == 'false'
        run: |
          NEW_REPO="Lesson_Python_TsingPig"
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.NEW_REPO_TOKEN }}" \
            https://api.github.com/user/repos \
            -d '{"name":"'$NEW_REPO'", "private":false}'

      - name: Sync folder to new repository
        run: |
          # 设置变量
          FOLDER_PATH="Algorithm/_____保研岛____Python蓝桥杯"
          NEW_REPO="Lesson_Python_TsingPig"
          NEW_REPO_URL="https://${{ secrets.NEW_REPO_TOKEN }}@github.com/${{ github.repository_owner }}/$NEW_REPO.git"

          # 创建新文件夹并复制内容
          mkdir $NEW_REPO
          cp -r "$FOLDER_PATH/" "$NEW_REPO/"

          # 初始化 Git 并推送
          cd $NEW_REPO
          git init
          git add .
          git commit -m "Synced folder from original repo"
          git remote add origin $NEW_REPO_URL
          git push -u origin main --force