name: Sync Folder
on:
  push:
    paths:
      - 'Algorithm/_____保研岛____Python蓝桥杯/**' # 监听文件夹的变化
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Check if new repository exists
        id: check_repo
        run: |
          NEW_REPO="Lesson_Python_TsingPig"
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.NEW_REPO_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository_owner }}/$NEW_REPO)
          if [ "$RESPONSE" -eq 200 ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create new repository if not exists
        if: steps.check_repo.outputs.exists == 'false'
        run: |
          NEW_REPO="Lesson_Python_TsingPig"
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.NEW_REPO_TOKEN }}" \
            https://api.github.com/user/repos \
            -d '{"name":"'$NEW_REPO'", "private":false}'

      - name: Clone new repository
        run: |
          NEW_REPO="Lesson_Python_TsingPig"
          NEW_REPO_URL="https://${{ secrets.NEW_REPO_TOKEN }}@github.com/${{ github.repository_owner }}/$NEW_REPO.git"

          # 克隆目标仓库，保留已有内容
          git clone $NEW_REPO_URL $NEW_REPO
          cd $NEW_REPO
          git checkout main

      - name: Sync folder content
        run: |
          # 设置变量
          SOURCE_FOLDER="Algorithm/_____保研岛____Python蓝桥杯"
          TARGET_FOLDER="Lesson_Python_TsingPig"

          # 仅同步文件夹内部内容，不覆盖目标仓库已有文件
          rsync -av --delete $SOURCE_FOLDER/ $TARGET_FOLDER/

      - name: Push changes to new repository
        run: |
          cd Lesson_Python_TsingPig
          git add .
          git commit -m "Sync latest changes from original repo" || echo "No changes to commit"
          git push origin main
